export const comparisonInputTableLabels = {
  item: "比較項目",
  diningCategory: "餐飲分類",
  people: "用餐人數",
  diningArea: "用餐區面積",
  kitchenArea: "廚房面積",
  effectiveVolume: "設備有效容積",
  designFlowCapacity: "設備設計流量 Q",
  greaseCapacity: "設備油脂能力 G",
  equipmentEvidence: "能力資料來源／證據",
  waterParameter: "用水量參數",
  useTime: "使用時間 t",
  areaParameters: "面積換算參數",
  safetyFactor: "安全係數 k",
  greaseCleaningPeriod: "油脂清除週期",
  sedimentCleaningPeriod: "殘渣清除週期",
  selectionBasis: "取值依據（選填）",
  supplementaryData: "補充資料（選填）",
} as const;
